language: android
jdk: oraclejdk8
sudo: required

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
 directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-19

    # Additional components
    - extra-google-m2repository
    - extra-android-support
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-19

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'intel-android-extra-license.+'
    - 'android-support-.+'

before_script:
  - mkdir -p app/build/intermediates/assets/release/
  - cp -R app/src/main/assets/sql/ app/build/intermediates/assets/release/sql
  - mkdir -p app/build/intermediates/assets/debug/
  - cp -R app/src/main/assets/sql/ app/build/intermediates/assets/debug/sql
  - mv app/src/debug/google-services.json app/google-services.json
  - mv app/src/debug/res/values/keys.xml app/src/main/res/values/keys.xml
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  
script:
  - ./gradlew test --stacktrace
  - ./gradlew connectedAndroidTest -i
